### ISSUE TITLE
App doesnt update without reloading service.

### ISSUE THREAD

**Issue by utzy79** [pantherale0/ha-fuelprices#25]
### System Health details

.

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/pantherale0/ha-fuelprices/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Hi there. Great app, been looking for something like this for years. But for some reason the priced dont update unless i reload the service manually.
I am assuming that this is not normal behavior but I cant seem to work out why?
I would be happy to have an automation that reloads the service, but cant seem to work out how to do that either without reloading all services.

### Reproduction steps

1.
2.
3.
...

### Debug logs

```text
.
```

**Comment by pantherale0** [comment]
Hi,

You shouldn't need to reload the integration to update data, although by default the refresh interval is set to 12 hours (I believe).

If you open an entity you should be see a `Last updated` attribute and `Next update`, can you check that those two attributes have updated after the next occurrence of `Next update` please?

![image](https://github.com/user-attachments/assets/abfde980-de8e-4030-93b9-2e3d56f43ae6)

**Comment by Rotil66** [comment]
Hi All,
I also have installed the integration and run into the same problem. I have seen that all the entities have a last update and a next update value that is corresponding with the set update interval, exept the Entities  sensor.cheapest 1,2,3,4,5 Here in the attributes the last update is 'undefined' and the 'next-update'is set to the date that the intergation is started not to the next interval time.
So it never updates anymore. This looks like a 'bug' or I am doing something wrong. The sensor for the cheapest stations is the one you want to use offcourse. 
Is there a solution to this ??

Thanks

**Comment by PeteLawler** [comment]
I'm wondering if the lack of update you're both seeing is same as the reason I'm not seeing an update.

In my logs, I'm getting this error. Whether it's the cause, I cannot say. The only reason I think it might is that clearly the update callback is failing. I had the Cheapest stuff enabled, but even turning it off didn't seem to fix the problem.


```
Error doing job: Task exception was never retrieved (None)

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 266, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 481, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 176, in async_update_listeners
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 561, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1007, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1132, in _async_write_ha_state
    self.__async_calculate_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1073, in __async_calculate_state
    if extra_state_attributes := self.extra_state_attributes:
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/fuel_prices/sensor.py", line 167, in extra_state_attributes
    return {
           ^
TypeError: 'NoneType' object is not a mapping
```

**Comment by utzy79** [comment]
I have found a work around for this, 
You need to create an automation that refreshes the service. Refer below

alias: Reload Fuel Prices app Every hour
description: ""
triggers:
  - trigger: time_pattern
    hours: /1
conditions: []
actions:
  - action: homeassistant.reload_config_entry
    metadata: {}
    data:
      entry_id: 01JC4K3HKRZRQTZ8EAVD9GKRPA
mode: single


For the entry ID you need to go into E:\.storage\core.config_entries
within this file search for 
"fuel_prices","entry_id"

![image](https://github.com/user-attachments/assets/31af6952-6fc4-4c11-9570-324fac01bf4a)


Next to this will be the code you need for entity ID.

**Comment by Rotil66** [comment]
Hi Utzy,
Thanks for this info. I will give it a try as soon as possible. Would be great if this works, so I can use the info as intended.

Thanks!

**Comment by Rotil66** [comment]
Hi Jordan,
this is something I'm also looking for.
Are you willing to share this with me/us.

thanks 

⁣BlueMail voor Android downloaden ​

Op 20 nov 2024 12:02, om 12:02, Jordan Harvey ***@***.***> schreef:

**Comment by pantherale0** [comment]
> Thank you for the work around, is working for me.

I need to warn, some providers are known to implement rate limits and block IPs if exceeded. Manually reloading the integration will override the update intervals.

It's not something I can recommend is done too frequently (hence the update interval in the config wizard has a lower limit of 3 hours I believe).

**Comment by Rotil66** [comment]
Hi Utzy,

I'm still a bit of a newby in HA.
So Inhave trouble finding core.config file for the ID. Can you tell me howbto find this in HA

thanks

⁣BlueMail voor Android downloaden ​

Op 20 nov 2024 08:23, om 08:23, utzy79 ***@***.***> schreef:

**Comment by utzy79** [comment]
You need to show hidden files and folders to see the folder.
For the automation, you should be able to create an automation from the editor, go to yaml then copy and paste from above overwriting the code in the new automation.
Then just change the entity id code to suit and save

**Comment by utzy79** [comment]
You need to install Samba share from the settings / addons section.
Not sure how to see hidden folders from inside HA as I dont use it that way

**Comment by Rotil66** [comment]
I have samba share running but HA is just not showing up  as share in windows. 
In Samba share I can see that the IP from my laptop is granted acces.
So this is confusing me.

**Comment by Rotil66** [comment]
> You need to show hidden files and folders to see the folder. For the automation, you should be able to create an automation from the editor, go to yaml then copy and paste from above overwriting the code in the new automation. Then just change the entity id code to suit and save.
> 
> I have my ha instance as a share folder so I can access it fromy laptop, much easier to edit Configs that way

Hi Utzy:
If I copy your code into a automation I get the error 'Extra key is not Allowed' Can you tell me what's going wrong ??

**Comment by Rotil66** [comment]
Hoi Utzy,
Sorry that it's starting toget a bit 'off topic'.
But if I copy you workaround or make my own Automation with your info, I get an error on saving;
**Message malformed: extra keys not allowed @ data['data']**
I can't find what i'm doing wrong here. Any Idea ??

**Comment by Rotil66** [comment]
HI Utzy,
It seems I have found the problem and you automation is running.  Now just wait for a price change to see if it is actually working.

**Comment by pantherale0** [comment]
@Rotil66 @utzy79 please continue this discussion either in Discord, the HA forums or in the discussion page of this repository. I've marked these comments as off topic because they have moved the discussion away from the actual issue itself.

**Comment by pantherale0** [comment]
> Hi Jordan, this is something I'm also looking for. Are you willing to share this with me/us. thanks ⁣BlueMail voor Android downloaden ​ Op 20 nov 2024 12:02, om 12:02, Jordan Harvey ***@***.***> schreef:

Hi, please find below template sensor configuration (to be used in the `templates` section of your configuration.yaml file).

```
- trigger: 
    - platform: state
      entity_id:
        - <sensor entity ID with long>
      attribute: longitude
    - platform: state
      entity_id:
        - <sensor entity ID with lat>
      attribute: latitude
    - platform: homeassistant
      event: start
    - platform: state
      entity_id:
        - input_button.force_update_fuels
        - input_boolean.use_cheapest_station
  action:
    - service: fuel_prices.find_fuel_station
      data:
        location:
          latitude: |
            {{ state_attr('<sensor entity ID with lat>', 'latitude') | float }}
          longitude: |
            {{ state_attr('<sensor entity ID with long>', 'longitude') | float }}
          radius: |
            {{ 5 * 1609.34 }}
      response_variable: data
    - variables:
        data: >
          {% if states('input_boolean.use_cheapest_station') == 'on' %}
            {{ data['items'] | sort(attribute='available_fuels.<fuel type code>') }}
          {% else %}
            {{ data['items'] | sort(attribute='distance') }}
          {% endif %}
  sensor:
    - name: Nearest Fuel Station
      unique_id: Nearest Fuel Station
      state: |
        {{ data[0].available_fuels.<fuel type code> | float }}
      availability: |
        {{ data | count > 0 }}
      state_class: measurement
      device_class: monetary
      unit_of_measurement: GBP
      attributes:
          other_stations: |
            {{ data }}
          latitude: |
            {{ data[0].latitude }}
          longitude: |
            {{ data[0].longitude }}
          name: |
            {{ data[0].name }}
          station: |
            {{ data[0] }}
```

Items that should be replaced for your liking:
`<sensor entity ID with lat>` = a device tracker or sensor that contains GPS coordinates
`<sensor entity ID with long>` = same as above
`<fuel type code>` = The fuel type to use (key as displayed in the entity attributes, diesel in the UK for example is `B7` but other countries will be different.

**Comment by pantherale0** [comment]
This should now be fixed in 2024.11.2

**Comment by Rotil66** [comment]
Thanks Jordan, I will add your code and see if It's updating the fuel prices without the workaround 👍🏻 Great work!!

**Comment by Rotil66** [comment]
Hi Jordan,
I have 2024.11.4 running but as far as I can see the prices are still not updated.
In attributes for cheapest stations the next next update is set to the date the service started and the last update is stil ' undefined'.
Will check longer but the issue seems remain.

**Comment by stevephi59** [comment]
Hi Rotil66,

If anything mine is updating the cheapest stations far too often, seems to be every 5 minutes. Maybe unrelated but I have also installed Jordan's template sensor.
I had also deleted the configuration before installing 2024.11.2 and recreated it afterwards. I had done this to try and overcome an error which suddenly started to appear after a reload of HA - error communicating with the API. I think my problem was with BP UK, however everything worked as expected after installing the latest code.


![fuel_prices_20241123_132632](https://github.com/user-attachments/assets/f2e42881-a1d2-4e80-8f24-f7e9d9c7832b)
![fuel_prices_20241123_132821](https://github.com/user-attachments/assets/bf1ef999-1e58-4c39-9431-58a956919170)

**Comment by pantherale0** [comment]
> If anything mine is updating the cheapest stations far too often, seems to be every 5 minutes. Maybe unrelated but I have also installed Jordan's template sensor.

This is intended, the update interval is set to every 5 minutes at the moment, to note, this is only from the location cache, no web requests should be sent unless the data source needs an update (as defined in the update interval).

**Comment by Rotil66** [comment]
Hi Jordan,

I just received the update of 2024.11.4 for the fuel price integration. 
Unfortunately now the integration is not running at all any more. Redownload reinstall etc etc. nothin is working.
It just saying that setup is failing and the intergration is not starting any more.
Any idea?

⁣BlueMail voor Android downloaden ​

Op 23 nov 2024 16:06, om 16:06, Jordan Harvey ***@***.***> schreef:

**Comment by pantherale0** [comment]
@Rotil66 please open a new issue.
